# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appinter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pushedexpress',
            old_name='userid',
            new_name='uuid',
        ),
    ]
